name: Jira Transition
description: Change status of specific Jira issue
branding:
  icon: 'chevron-right'
  color: 'blue'
inputs:
  transition:
    description: The transition to apply to the issue, e.g. 'In Progress'
    required: false
  transitionId:
    description: The id of a transition to apply to the issue
    required: false
runs:
  using: 'node12'
  main: './dist/index.js'
